### ISSUE TITLE
In the case of do not specify "table" in "select" method, you can not  use index_hint.

### ISSUE THREAD

**Issue by akihiro0228** [tokuhirom/SQL-Maker#45]
If you specify "joins" in "select" method, it is not necessary to specify the "table".

> https://github.com/tokuhirom/SQL-Maker/blob/master/lib/SQL/Maker.pm#L277-L281
> https://github.com/tokuhirom/SQL-Maker/blob/master/lib/SQL/Maker/Select.pm#L170

In the case of do not specify "table" in "select" method, you can not  use index_hint.

In the case of "$table" valiable is undef in "add_index_hint" method,

```
$self->{index_hint}->{undef} = {
    type => $type,
    list => $list,
};
```

is error.

> https://github.com/tokuhirom/SQL-Maker/blob/master/lib/SQL/Maker/Select.pm#L127-L130

In other words, if only use the "joins", you can not use the "index_hint".

> https://github.com/tokuhirom/SQL-Maker/blob/master/lib/SQL/Maker/Select.pm#L169

Please and to be able to register the "index_hint" without specifying "table".

**Comment by tokuhirom** [comment]
patches welcome

**Comment by akihiro0228** [comment]
thanks! 😄
